Repository Cyber4All/rating-service, pull requests merged in 2019-02, with the labels that each got.

#17 query by authorId and name
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/routes.ts
Labels: bug, review

#18 Update Raven to Sentry
  package-lock.json
  package.json
  src/drivers/MongoDriver.ts
  src/drivers/SentryConnector.ts
  src/drivers/express/ExpressDriver.ts
  src/ratings/RatingAuthorization.ts
  src/ratings/RatingStore.ts
Labels: enhancement, review

#19 Remove $toString and add toString helper methods in RatingStore
  package-lock.json
  package.json
  src/ratings/RatingStore.spec.ts
  src/ratings/RatingStore.ts
  src/ratings/RatingsInteractor.ts
  src/ratings/RatingsRouteHandler.ts
  src/ratings/interfaces/RatingDataStore.ts
  src/ratings/mocks/MockObjects.ts
Labels: bug, review

#20 Add check for null id
  package-lock.json
  package.json
  src/ratings/RatingStore.ts
Labels: review
